### ISSUE TITLE
sst-macro/skeletons/tests/sendrecv Cannot find builder error

### ISSUE THREAD

**Issue by yao-kang** [sstsimulator/sst-macro#503] opened 2019-11-29 05:25 UTC
After building sst-core and sst-elements, following test simulation can be executed
`sst sst-elements/src/sst/elements/simpleElementExample/tests/test_simpleRNGComponent_mersenne.py`

Then sst-macro is built with sst-core. Building process finished without any error from `make check` and `make installcheck` 
However when trying to run the test program, the following error appears:
`$ pysstmac -f parameters.ini` 
`error: cannot find builder 'runsendrecv' in library 'macro' for base type App
../../../sprockit/sprockit/factory.h 257` 

Am I missing something here? Thanks

**Comment by calewis** [comment] 2019-12-02 17:47
Hello Yao, 

I also get this same error, although after a little bit of digging I am still unsure what the issue is.  I suspect that this may be related to recent changes, but can't confirm 100%.  I have assigned this issue to @jjwilke since he is the most likely to be able to quickly fix this, but he may not be able to respond for some time.  Sorry for the inconvenience.

**Comment by yao-kang** [comment] 2019-12-02 19:46
Hello Drew,

Thanks for the help. I will try with the previous version to see if the error is persistent.

**Comment by jpkenny** [comment] 2019-12-04 01:06
I've verified that this is a bug.  I'm not certain if sst-core currently supports multiple apps (this is certainly supported in standalone mode, but the error message and documentation should be improved regardless).  @jjwilke can follow up when he's back.  The app runs fine if you only run one instance, for example changing the parameters.ini file to:

include small_torus.ini
  
node {
 app1 {
  launch_cmd = aprun -n 2 -N 1
  name = runsendrecv
 }
# app2 {
#  launch_cmd = aprun -n 2 -N 2
#  name = runsendrecv
# }
}

**Comment by yao-kang** [comment] 2019-12-04 01:31
> The app runs fine if you only run one instance, for example changing the parameters.ini file to:

Changing the parameters.ini file with only one app does do the trick. Thanks!

**Comment by jjwilke** [comment] 2020-04-10 15:28
This appears to be fixed with the new input.

**Closed by jjwilke** 2020-04-10 15:28 UTC
Labels: bug
